### ISSUE TITLE
Error Encountered when following the documentation

### ISSUE THREAD

**Issue by Redstone-Hamster** [distubejs/example#8]
Error: play(fake woke) encountered:
Error parsing info: Unable to retrieve video metadata
    at getWatchPage (/home/runner/Moderatrix/node_modules/ytdl-core/lib/info.js:75:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async exports.getBasicInfo (/home/runner/Moderatrix/node_modules/ytdl-core/lib/info.js:84:22)
    at async Map.getOrSet (/home/runner/Moderatrix/node_modules/ytdl-core/lib/cache.js:24:19)
    at async exports.getInfo (/home/runner/Moderatrix/node_modules/ytdl-core/lib/info.js:226:14)
    at async Map.getOrSet (/home/runner/Moderatrix/node_modules/ytdl-core/lib/cache.js:24:19)
    at async DisTube._resolveSong (/home/runner/Moderatrix/node_modules/distube/src/DisTube.js:192:55)
    at async DisTube.play (/home/runner/Moderatrix/node_modules/distube/src/DisTube.js:243:44)
    at async Client.<anonymous> (/home/runner/Moderatrix/server.js:803:9)
I followed the example but I keep getting this error. Why?

**Comment by skick1234** [comment]
Read README. Update dependencies.
